version: 0.2

phases:
  install:
    runtime-versions:
      java: coretto17

  pre_build:
    commands:
      - echo skipped on `date`

  build:
    commands:
      - echo Building the Java code
      - cd user
      - java -version

  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - user/target/spring-boot.jar
