spring:
  jpa:
    open-in-view: false
  application:
    name: login
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_login}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:simple_password}
  mail:
    host: ${SMTP_HOST:smtp.mailgun.org}
    port: ${SMTP_PORT:587}
    username: ${SMTP_USER:login-api@pedroscarelli.com}
    password: ${SMTP_PASS:simple-pass}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
      expiration: ${JWT_EXPIRATION_SECONDS:7200}
      issuer: ${JWT_ISSUER:login-api}
  base-url: ${API_BASE_URL:http://localhost:8080}
