spring:
  jpa:
    open-in-view: false
  application:
    name: login
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:db_login}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:simple-password}

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}
      expiration: ${JWT_EXPIRATION_SECONDS:7200}
      issuer: ${JWT_ISSUER:login-api}

