version: "3.8"

services:
  app:
    image: "docker-spring-boot-postgres:latest"
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      - POSTGRES_USER=cceqwqtauwdmaz
      - POSTGRES_PASSWORD=08d775d29ca397ff0510b0e3d16270be7a3cf021936b899cdc2ad6c87aa029e6
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ec2-52-0-79-72.compute-1.amazonaws.com:5432/dfmiedic6bmbbo
      - SPRING_DATASOURCE_USERNAME=cceqwqtauwdmaz
      - SPRING_DATASOURCE_PASSWORD=08d775d29ca397ff0510b0e3d16270be7a3cf021936b899cdc2ad6c87aa029e6
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "8080:8080"

  db:
    image: postgres
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=copySauce
      - POSTGRES_DB=login
    ports:
      - "5432:5432"
